### ISSUE TITLE
Error on terraform deployment with AWS UnsupportedAvailabilityZoneException (us-east-1c))

### ISSUE THREAD

**Issue by okynos** [jenkins-x/terraform-aws-eks-jx#71] opened 2020-06-03 16:01 UTC
Hello Jenkins-X team,

As I said here https://kubernetes.slack.com/archives/C9MBGQJRH/p1591192617327400 I detected a problem with terraform and AWS deployment of Jenkins-X.

I'm having the following error:
```
Error: error creating EKS Cluster (tf-jx-nearby-cod): UnsupportedAvailabilityZoneException: Cannot create cluster 'tf-jx-nearby-cod' because us-east-1c, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1d, us-east-1e, us-east-1f
```

Steps to reproduce:
1. Go to https://jenkins-x.io/docs/getting-started/
2. Create `main.tf` file as described on docs.
3. Configure AWS credentials (suppose AWS cli).
4. run `terraform init`.
5. run `terraform apply` (error received in the middle of launch (resource 30 of 74)).

Regards.

**Comment by vfarcic** [comment] 2020-06-03 16:06
I'm experiencing the same issue right now (creating a new cluster for a demo).

The problem is on AWS side. One of the zones is full. If the zone is not important (as in my case), switching to a different region works (I'm creating it right now in us-east-2). Otherwise, if it must be us-east1, your best bet is to wait until AWS resolves it. Alternatively, you can skip using that zone and focus on the rest of the zones in that region.

**Comment by vfarcic** [comment] 2020-06-03 16:13
I'll close the issue since it's not directly related to JX and since there is not much we can do to fix it. Please reopen if that doesn't sound right.

**Closed by vfarcic** 2020-06-03 16:13 UTC
