### ISSUE TITLE
Unable to destroy cluster with timeout on aws_internet_gateway destruction

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/terraform-aws-eks-jx#36] opened 2020-04-28 11:13 UTC
After installing Jenkins X a `terraform destroy` fails with:

```
module.eks-jx.module.cluster.module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-02deb1c3a69fc3b48, 14m50s elapsed]

Error: Error waiting for internet gateway (igw-02deb1c3a69fc3b48) to detach: timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)



Error: timeout while waiting for resource to be gone (last state: 'Terminating', timeout: 5m0s)



Error: error deleting S3 Bucket (logs-hardy-tf-jx-20200424063048248600000005): BucketNotEmpty: The bucket you tried to delete is not empty
	status code: 409, request id: 8F7DC8F3201C0660, host id: Ql4eaqlM6/d3pPc11DuA0sMnPKiQVM36sQ3lWVB3VRN/E05MvoL/lSSZ0EharZ7XtP1w2fHptYE=
```

**Comment by vfarcic** [comment] 2020-04-28 11:20
I experienced the same problem (not through the same Terraform definition) caused by Ingress. It created NLB which needs to be destroyed before running `terraform destroy`.

**Comment by hferentschik** [comment] 2020-04-28 12:12
> I experienced the same problem (not through the same Terraform definition) caused by Ingress. It created NLB which needs to be destroyed before running terraform destroy.

We need to improve on this. I think a destroy should be possible w/o having to remember to call `jx uninstall` first or manually deleting some resources.

**Comment by zakswindow** [comment] 2020-04-29 00:11
> I experienced the same problem (not through the same Terraform definition) caused by Ingress. It created NLB which needs to be destroyed before running `terraform destroy`.

There is an easy fix for this.
  **Change** 
```
desired_node_count = "0"
max_node_count     = "0"
min_node_count     = "0"
```

and then run "terraform apply" and then "terraform destroy". Thats all.

**Comment by vfarcic** [comment] 2020-05-12 17:57
I would suggest to destroy through Terraform all NLB/ELB load balancers that match the tags.

**Comment by vfarcic** [comment] 2020-06-02 13:12
Any news about this issue?

**Comment by ankitm123** [comment] 2020-06-02 16:23
@vfarcic I created this issue (weird I missed this issue): https://github.com/jenkins-x/terraform-aws-eks-jx/issues/54 (I will close mine in favor of this). I am going to take a look at it soon, it has created issues for me in the past. This is most probably related to this: https://github.com/terraform-providers/terraform-provider-aws/issues/10934#issuecomment-558289840 (but need to look more).

**Closed** 2020-11-30 12:05 UTC
Labels: area/terraform, kind/bug, lifecycle/rotten

**Comment by Karthikraja9** [comment] 2024-03-27 05:32
This issue has started to re-occur in Terraform 1.7.5-
Error: deleting EC2 Internet Gateway (igw-xxxxxxxxxxxxxxxxx): detaching EC2 Internet Gateway (igw-xxxxxxxxxxxxxxxxx) from VPC (vpc-xxxxxxxxxxxxxxxxx): DependencyViolation: Network vpc-xxxxxxxxxxxxxxxx has some mapped public address(es). Please unmap those public address(es) before detaching the gateway. status code: 400

The Public IP its referring to is attached to the Load balancer, still Terraform is trying to delete the Internet Gateway first and then the LB which is resulting in the above error.
Note: LB termination protection is off.
